site_name: NOMAD Parser Writing Documentation
site_description: |
  NOMAD documentation on how to write and extend parsers.
site_author: FAIRmat consortium
nav:
  - Overview: index.md
  - Creating the shell for your parser: parser_shell.md
  - Parser structure for computation: computational.md
  - Creating parser tests: parser_tests.md
  - Creating new metainfo: creating_new_metainfo.md
  - References:
    - Quick Start - parser setup: references/quick_parser_setup.md
    - Quick Start - installing a development version of NOMAD: references/quick_installing_nomad_dev.md
    - Quick Start - best practices for NOMAD development: references/quick_NOMAD_best_practices.md
    - Examples - NOMAD's parser-matching interface: references/examples_parser_matching.md
    - Examples - populating the NOMAD archive: references/examples_populating_archive.md
    - Standard workflows in NOMAD: references/standard_workflows.md
    - Advanced - creating a new parser project: references/advanced_new_parser_project.md
    - Old Docs: references/old_docs.md
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/nomad-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css

